### ISSUE TITLE
Create Go script to batch convert YAML fingerprints to JSON format

### ISSUE THREAD

**Issue by 4ra1n** [jar-analyzer/jar-analyzer#167]
# YAML to JSON Converter

Need to create a Go script that processes YAML fingerprint files and generates corresponding JSON files with specific format.

## Requirements

1. Input: YAML files with the following structure:
```yaml
name: yaml-fingerprint-linux_mint-linuxmint
binding: 0a0dca86-4781-44f9-9f1b-34e90d0fba77
manual: false
detail:
  author: luhan.xu
  fingerprint:
    id: d5ef88f8-0a33-4692-a0a3-6e8f517e0c52
    name: Linux Mint 17.0
    cpe: cpe:2.3:o:linuxmint:linux_mint
# ... rest of the YAML structure
```

2. Output: JSON files with the following format:
```json
{
    "name": "__name__",
    "author": "qingyxu",
    "version": "0.0.0",
    "level": "-1",
    "matches": [
        {
            "search": "body",
            "text": "todo"
        }
    ],
    "condition": "0"
}
```

## Processing Rules

1. Generate output filename based on `detail.fingerprint.name` from the YAML file
   - Replace spaces with underscores in the filename
2. In the JSON content:
   - Replace `__name__` with the original `detail.fingerprint.name` value

## Implementation Tasks

1. Create a Go script that can:
   - Read YAML files from a specified directory
   - Parse YAML structure
   - Extract required information
   - Generate corresponding JSON files
   - Handle error cases (invalid YAML, missing fields, etc.)

2. Include proper error handling and logging

3. Add validation to ensure:
   - Required fields exist in YAML
   - Generated JSON is valid
   - No duplicate files are created

## Technical Considerations

- Use Go's YAML parsing libraries (e.g., gopkg.in/yaml.v3)
- Use encoding/json for JSON generation
- Implement concurrent processing for better performance
- Add tests for the conversion logic
